### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by saigkill** [fletcher/peg-multimarkdown#154]
I tried a Linux (Ubuntu 15.10) build of peg-multimarkdown by following this manual: https://github.com/fletcher/peg-multimarkdown#linux

Actually i'm getting after 'make':

> sascha@sascha-desktop:~/repos/git/github-peg-multimarkdown$ make
> CC=gcc make -C peg-0.1.9
> make[1]: Entering directory '/home/sascha/repos/git/github-peg-multimarkdown/peg-0.1.9'
> gcc -g -Wall -O3 -DNDEBUG    -c -o peg.o peg.c
> In file included from peg.c:48:0:
> peg.peg-c: In function ‘yy_Sequence’:
> peg.peg-c:791:3: warning: label ‘l77’ defined but not used [-Wunused-label]
>    l77:;   ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
>    ^
> In file included from peg.c:48:0:
> peg.c: At top level:
> peg.peg-c:226:16: warning: ‘yyPush’ defined but not used [-Wunused-function]
> YY_LOCAL(void) yyPush(yycontext *ctx, char *text, int count)  { ctx->val += count; }
>                 ^
> peg.peg-c:227:16: warning: ‘yyPop’ defined but not used [-Wunused-function]
> YY_LOCAL(void) yyPop(yycontext *ctx, char *text, int count)   { ctx->val -= count; }
>                 ^
> peg.peg-c:228:16: warning: ‘yySet’ defined but not used [-Wunused-function]
> YY_LOCAL(void) yySet(yycontext *ctx, char *text, int count)   { ctx->val[count]= ctx->yy; }
>                 ^
> gcc -g -Wall -O3 -DNDEBUG    -c -o tree.o tree.c
> gcc -g -Wall -O3 -DNDEBUG    -c -o compile.o compile.c
> gcc -g -Wall -O3 -DNDEBUG  -o peg-new peg.o tree.o compile.o
> mv peg-new peg
> ./leg -o leg.c leg.leg
> make[1]: ./leg: Befehl nicht gefunden
> Makefile:39: recipe for target 'leg.c' failed
> make[1]: *** [leg.c] Error 127
> make[1]: Leaving directory '/home/sascha/repos/git/github-peg-multimarkdown/peg-0.1.9'
> Makefile:50: recipe for target 'peg-0.1.9/leg' failed
> make: *** [peg-0.1.9/leg] Error 2

Do i need to install other dependencies first?

**Comment by fletcher** [comment]
This program has not been active for many years (as per the project description), suggest you use MultiMarkdown 5 instead:

https://github.com/fletcher/MultiMarkdown-5
