### ISSUE TITLE
Epub export customisation

### ISSUE THREAD

**Issue by actuallymentor** [fletcher/peg-multimarkdown#155]
Hello!

Thank you so much for writing this and to include epub3 support. I can't seem to find epub3 documentation for this package, is there anywhere I can get info?

I'm happy to translate external/technical documentation to a wiki PR.

Edit: typo

**Comment by fletcher** [comment]
This project has been deprecated for quite  a while.  The latest version is [here](https://github.com/fletcher/MultiMarkdown-6).

What sort of customization are you looking to do?  EPUB is basically just HTML wrapped up in a zip file, with a few extra index files.  You customize it the same way you customize HTML -- CSS.

**Comment by actuallymentor** [comment]
That was all the info I needed, being able to apply a stylesheet solves it :)
